# Generated by Django 4.2.16 on 2025-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0011_create_family_sms_and_alter_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicationofpolicynotifications',
            name='confirmation_of_policy_periodic_payment',
            field=models.DateTimeField(db_column='NotificationOnPolicyPeriodicConfirmationSent', null=True),
        ),
        migrations.AddField(
            model_name='indicationofpolicynotifications',
            name='payment_of_policy_periodic',
            field=models.DateTimeField(db_column='NotificationOnPolicyPeriodicPaymentSent', null=True),
        ),
        migrations.AddField(
            model_name='indicationofpolicynotifications',
            name='payment_request_for_paamg',
            field=models.DateTimeField(db_column='NotificationOnPaymentRequestPAAMGSent', null=True),
        ),
        migrations.AddField(
            model_name='indicationofpolicynotifications',
            name='payment_request_for_policiy_activation',
            field=models.DateTimeField(db_column='NotificationOnPaymentRequestSent', null=True),
        ),
    ]
