# Generated by Django 4.2.16 on 2025-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0012_indicationofpolicynotifications_confirmation_of_policy_periodic_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicationofpolicynotifications',
            name='payment_request_for_policiy_activation_vulnerable',
            field=models.DateTimeField(db_column='NotificationOnPaymentRequestSentVulnerable', null=True),
        ),
    ]
